### ISSUE TITLE
VSCode and WSL(Ubuntu20.04LTS) visualization crash with mouseklick (left and right)

### ISSUE THREAD

**Issue by slyandsmart** [jgerstmayr/EXUDYN#47] opened 2023-05-31 08:47 UTC
WSL with Ubuntu20.04LTS on Windows10 
VSCode: 1.78.2
Python: 3.8.10
Exudyn:  1.6.119.dev1

Left and right mouse klick on the visualization window crashes the simulation. 
No error code given. 

Setting following disables the mouse klick for selection and leads to no crash afterwards. 
    SC.visualizationSettings.interactive.selectionLeftMouse=False
    SC.visualizationSettings.interactive.selectionRightMouse=False

Zoom and view in the simulation is still possible.

**Comment by jgerstmayr** [comment] 2023-06-01 06:52
It seems to be related to WSL version and possible the viewer mode. Can you add WSL version (possibly try updating WSL)? Which viewer do you use (standard WSL?)
stable behavior is observed if you use (add this to .bashrc):
export DISPLAY=:0
export LIBGL_ALWAYS_INDIRECT=0
The latter command slows down visualization for larger models or shadows but is rather stable. 

Simply try visualization with:
import exudyn
exudyn.demos.Demo2()

**Comment by jgerstmayr** [comment] 2023-06-08 19:57
for now, it seems to be the best solution to either use Windows or pure linux or to set
SC.visualizationSettings.interactive.selectionLeftMouse=False
SC.visualizationSettings.interactive.selectionRightMouse=False

**Comment by jgerstmayr** [comment] 2023-06-19 20:31
This seems to be caused by OpenGL; resolved by setting:
export LIBGL_ALWAYS_SOFTWARE=0
preferably, put this into your .bashrc

**Closed by jgerstmayr** 2023-06-19 20:31 UTC
